# Generated by Django 2.2.7 on 2019-12-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.FloatField(default=20.0, max_length=9),
            preserve_default=False,
        ),
    ]
